ext {
    mod_id          = "geostrata"
    mod_name        = "GeoStrata"
    mod_group_id    = "reika.geostrata"
    mod_description = "GeoStrata adds realistic rock layers and geology-based content to the world."
}

dependencies {
    implementation project(":DragonAPI")
    implementation project(":RotaryCraft")
}
