package reika.geostrata.data;

import com.google.common.collect.ImmutableList;
import com.google.gson.JsonObject;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.levelgen.GenerationStep;
import reika.geostrata.GeoStrata;

import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.CompletableFuture;

/**
 * 26.2 biome modifier data provider for GeoStrata.
 * <p>
 * Generates {@code data/geostrata/neoforge/biome_modifier/*.json} as literal JSON because
 * {@code RegistrySetBuilder} cannot resolve biome tags during datagen.
 * Most modifiers target {@code #minecraft:is_overworld}; the rock modifier targets every biome
 * and lets {@code RockGenerator} apply its dimension config at placement time. Each references a placed feature
 * that was generated by {@link GeoWorldGenProvider}'s {@code RegistrySetBuilder}.
 * </p>
 */
public final class GeoBiomeModifierProvider implements DataProvider {

    /** One JSON per {@code id}; {@code feature} is the placed feature it points at (default: same as id). */
    private record Entry(String id, String feature, GenerationStep.Decoration step, String biomes) {
        Entry(String id, GenerationStep.Decoration step) {
            this(id, id, step, "#minecraft:is_overworld");
        }
        Entry(String id, GenerationStep.Decoration step, String biomes) {
            this(id, id, step, biomes);
        }
    }
    private static final List<Entry> ENTRIES = List.of(
            new Entry("geo_rock",      GenerationStep.Decoration.UNDERGROUND_DECORATION),
            new Entry("glow_crystal",  GenerationStep.Decoration.SURFACE_STRUCTURES),
            new Entry("glowing_vine",  GenerationStep.Decoration.UNDERGROUND_DECORATION),
            new Entry("lava_rock",     GenerationStep.Decoration.UNDERGROUND_ORES),
            new Entry("ocean_spike",   GenerationStep.Decoration.LOCAL_MODIFICATIONS),
            new Entry("rf_crystal",    GenerationStep.Decoration.UNDERGROUND_ORES),
            new Entry("vent",          GenerationStep.Decoration.UNDERGROUND_ORES),
            new Entry("vent_nether", "vent", GenerationStep.Decoration.UNDERGROUND_ORES, "#minecraft:is_nether"),
            new Entry("vent_end", "vent", GenerationStep.Decoration.UNDERGROUND_ORES, "#minecraft:is_end"),
            new Entry("void_opal",     GenerationStep.Decoration.LOCAL_MODIFICATIONS, "#minecraft:is_end"),
            new Entry("ore_vein",      GenerationStep.Decoration.UNDERGROUND_DECORATION),
            new Entry("ore_vein_nether", "ore_vein", GenerationStep.Decoration.UNDERGROUND_DECORATION, "#minecraft:is_nether"),
            new Entry("ore_vein_end",    "ore_vein", GenerationStep.Decoration.UNDERGROUND_DECORATION, "#minecraft:is_end"),
            //Last step so its tree/leaf clearing runs after vegetation, like legacy post-populate retrogen.
            new Entry("arctic_spire",  GenerationStep.Decoration.TOP_LAYER_MODIFICATION),
            new Entry("creepvine",     GenerationStep.Decoration.VEGETAL_DECORATION)
    );

    private final PackOutput.PathProvider pathProvider;

    public GeoBiomeModifierProvider(PackOutput output) {
        this.pathProvider = output.createPathProvider(PackOutput.Target.DATA_PACK, "neoforge/biome_modifier");
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        ImmutableList.Builder<CompletableFuture<?>> futures = ImmutableList.builder();
        for (var entry : ENTRIES) {
            Identifier id = Identifier.fromNamespaceAndPath(GeoStrata.MODID, entry.id);
            Identifier feature = Identifier.fromNamespaceAndPath(GeoStrata.MODID, entry.feature);
            Path path = pathProvider.json(id);
            futures.add(CompletableFuture.supplyAsync(() -> {
                JsonObject json = new JsonObject();
                json.addProperty("type", entry.id.equals("geo_rock")
                        ? "geostrata:all_biomes_features" : "neoforge:add_features");
                if (!entry.id.equals("geo_rock")) json.addProperty("biomes", entry.biomes);
                json.addProperty("features", feature.toString());
                json.addProperty("step", entry.step.getName());
                return json;
            }).thenComposeAsync(encoded -> DataProvider.saveStable(cache, encoded, path)));
        }
        return CompletableFuture.allOf(futures.build().toArray(CompletableFuture[]::new));
    }

    @Override
    public String getName() {
        return "GeoStrata Biome Modifiers";
    }
}
