package reika.geostrata.data;

import com.google.common.collect.ImmutableList;
import com.google.gson.JsonObject;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.levelgen.GenerationStep;
import reika.geostrata.GeoStrata;

import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.CompletableFuture;

/**
 * 26.2 biome modifier data provider for GeoStrata.
 * <p>
 * Generates {@code data/geostrata/neoforge/biome_modifier/*.json} as literal JSON because
 * {@code RegistrySetBuilder} cannot resolve biome tags during datagen.
 * Each modifier targets {@code #minecraft:is_overworld} and references a placed feature
 * that was generated by {@link GeoWorldGenProvider}'s {@code RegistrySetBuilder}.
 * </p>
 */
public final class GeoBiomeModifierProvider implements DataProvider {

    private static final record Entry(String id, GenerationStep.Decoration step) {}
    private static final List<Entry> ENTRIES = List.of(
            new Entry("geo_rock",      GenerationStep.Decoration.UNDERGROUND_DECORATION),
            new Entry("glow_crystal",  GenerationStep.Decoration.SURFACE_STRUCTURES),
            new Entry("glowing_vine",  GenerationStep.Decoration.UNDERGROUND_DECORATION),
            new Entry("lava_rock",     GenerationStep.Decoration.UNDERGROUND_ORES),
            new Entry("ocean_spike",   GenerationStep.Decoration.LOCAL_MODIFICATIONS),
            new Entry("rf_crystal",    GenerationStep.Decoration.UNDERGROUND_ORES),
            new Entry("vent",          GenerationStep.Decoration.UNDERGROUND_ORES)
    );

    private final PackOutput.PathProvider pathProvider;

    public GeoBiomeModifierProvider(PackOutput output) {
        this.pathProvider = output.createPathProvider(PackOutput.Target.DATA_PACK, "neoforge/biome_modifier");
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        ImmutableList.Builder<CompletableFuture<?>> futures = ImmutableList.builder();
        for (var entry : ENTRIES) {
            Identifier id = Identifier.fromNamespaceAndPath(GeoStrata.MODID, entry.id);
            Path path = pathProvider.json(id);
            futures.add(CompletableFuture.supplyAsync(() -> {
                JsonObject json = new JsonObject();
                json.addProperty("type", "neoforge:add_features");
                json.addProperty("biomes", "#minecraft:is_overworld");
                json.addProperty("features", id.toString());
                json.addProperty("step", entry.step.getName());
                return json;
            }).thenComposeAsync(encoded -> DataProvider.saveStable(cache, encoded, path)));
        }
        return CompletableFuture.allOf(futures.build().toArray(CompletableFuture[]::new));
    }

    @Override
    public String getName() {
        return "GeoStrata Biome Modifiers";
    }
}
