package reika.geostrata.data;

import net.minecraft.data.PackOutput;
import net.minecraft.world.item.BlockItem;
import net.neoforged.neoforge.common.data.LanguageProvider;
import reika.geostrata.GeoStrata;
import reika.geostrata.registry.GeoBlocks;

import java.util.Locale;

/**
 * en_us language provider for GeoStrata.
 * <p>
 * Iterates the mod's block / item DeferredRegisters and emits humanised names. Most rock-type
 * blocks are registered via {@link reika.geostrata.registry.RockShapes#register} which runs
 * during {@code GeoBlocks.initialise(bus)}, so they appear in the entry collections too.
 */
public class GeoLang extends LanguageProvider {

    public GeoLang(PackOutput output, String locale) {
        super(output, GeoStrata.MODID, locale);
    }

    @Override
    protected void addTranslations() {
        add("tab.geostrata", "GeoStrata");
        add("tab.geostrata_ores", "GeoStrata Ores");
        add("tab.geostrata_stairs", "GeoStrata Stairs");
        add("tab.geostrata_slabs", "GeoStrata Slabs");

        GeoBlocks.BLOCKS.getEntries().forEach(holder ->
                addBlock(holder, prettify(holder.getId().getPath())));

        // ITEMS contains BlockItems for every Block (auto-generated by DeferredRegister.Blocks)
        // plus standalone items. BlockItem's description id is `block.<modid>.<path>` — the same
        // key addBlock already emitted — so addItem would throw on duplicate. Filter them out.
        GeoBlocks.ITEMS.getEntries().forEach(holder -> {
            if (holder.get() instanceof BlockItem) return;
            addItem(holder, prettify(holder.getId().getPath()));
        });
    }

    private static String prettify(String path) {
        String[] parts = path.split("_");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            if (i > 0) sb.append(' ');
            String p = parts[i];
            if (p.isEmpty()) continue;
            sb.append(Character.toUpperCase(p.charAt(0)));
            if (p.length() > 1) sb.append(p.substring(1).toLowerCase(Locale.ROOT));
        }
        return sb.toString();
    }
}
