package reika.geostrata.data;

import net.minecraft.data.PackOutput;
import net.minecraft.world.item.BlockItem;
import net.neoforged.neoforge.common.data.LanguageProvider;
import reika.geostrata.GeoStrata;
import reika.geostrata.registry.GeoBlocks;
import reika.geostrata.registry.GeoItems;
import reika.geostrata.base.VentType;

import java.util.Locale;

/**
 * en_us language provider for GeoStrata.
 * <p>
 * Iterates the mod's block / item DeferredRegisters and emits humanised names. Most rock-type
 * blocks are registered via {@link reika.geostrata.registry.RockShapes#register} which runs
 * during {@code GeoBlocks.initialise(bus)}, so they appear in the entry collections too.
 */
public class GeoLang extends LanguageProvider {

    public GeoLang(PackOutput output, String locale) {
        super(output, GeoStrata.MODID, locale);
    }

    @Override
    protected void addTranslations() {
        add("tab.geostrata", "GeoStrata");
        add("tab.geostrata_stone", "GeoStrata Stones");
        add("tab.geostrata_ores", "GeoStrata Ores");
        add("tab.geostrata_stairs", "GeoStrata Stairs");
        add("tab.geostrata_slabs", "GeoStrata Slabs");
        add("config.jade.plugin_geostrata.survival_data", "GeoStrata Details");
        add("jade.geostrata.rock_properties", "%sR / %sH");
        add("jade.geostrata.depleted", "Depleted");
        add("jade.geostrata.potential_yields", "Potential Yields:");
        add("jade.geostrata.yield", "%s %s%%");
        add("jade.geostrata.inexhaustible", "Inexhaustible");
        add("jade.geostrata.remaining", "%s Items Remaining");
        add("jade.geostrata.no_root", "[No Root Found]");
        add("jade.geostrata.energy", "%s / %s RF");
        add("jade.geostrata.inactive", "Inactive");
        add("jade.geostrata.vent", "%s Vent: %s");
        add("jade.geostrata.erupting", "Erupting");
        add("jade.geostrata.dormant", "Dormant");
        for (VentType type : VentType.values())
            add("jade.geostrata.vent_type." + type.getName(), prettify(type.getName()));

        for (int i = 0; i < 4; i++)
            add("item.geostrata.lava_rock_item_" + i, "Lava Rock");

        GeoBlocks.BLOCKS.getEntries().forEach(holder ->
                addBlock(holder, prettify(holder.getId().getPath())));

        // ITEMS contains BlockItems for every Block (auto-generated by DeferredRegister.Blocks)
        // plus standalone items. BlockItem's description id is `block.<modid>.<path>` — the same
        // key addBlock already emitted — so addItem would throw on duplicate. Filter them out.
        GeoBlocks.ITEMS.getEntries().forEach(holder -> {
            if (holder.get() instanceof BlockItem) return;
            addItem(holder, holder.get() == GeoItems.LOW_TEMP_DIAMONDS.get()
                    ? "Low-Temperature Diamonds" : prettify(holder.getId().getPath()));
        });
    }

    private static String prettify(String path) {
        String[] parts = path.split("_");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            if (i > 0) sb.append(' ');
            String p = parts[i];
            if (p.isEmpty()) continue;
            sb.append(Character.toUpperCase(p.charAt(0)));
            if (p.length() > 1) sb.append(p.substring(1).toLowerCase(Locale.ROOT));
        }
        return sb.toString();
    }
}
