package reika.geostrata.block;

import net.minecraft.world.level.block.Block;

import reika.dragonapi.interfaces.block.ConnectedModelBlock;

/**
 * Connected-texture rock (the CONNECTED / CONNECTED2 shapes). All rendering is handled by DragonAPI's
 * {@code dragonapi:connected_overlay} blockstate model (see the static blockstate JSONs under
 * {@code assets/geostrata/blockstates/}, generated by {@code scripts/gen_geo_connected_blockstates.py})
 * — the block itself only supplies the connectivity rule, and since every (rock type, shape) pair is
 * registered as its own Block instance, the {@link ConnectedModelBlock} default (same block) is
 * exactly the legacy "same rock type and same shape" test.
 *
 * <p>The previous port carried the legacy icon-array fields ({@code SimpleTexture[][]}) and a
 * numpad-edge helper wired to a renderer that was never invoked (and crashed when it was) — all of
 * that now lives in {@code reika.dragonapi.instantiable.rendering.connected.ConnectedQuads}.</p>
 */
public class BlockConnectedRock extends Block implements ConnectedModelBlock {

	public BlockConnectedRock(Properties properties) {
		super(properties);
	}
}
